@extends('pages.settings.base')

@section('meta-page-title', $credential->exists ? 'Edit credential' : 'Add credential')
@section('page-title', $credential->exists ? 'Edit credential' : 'Add credential')

@section('page-sub-content')
	<div class="card-body"><form action="{{ $credential->exists ? route('settings.templates.credentials.update', $credential) : route('settings.templates.credentials.store') }}" method="POST">@csrf @if ($credential->exists) @method('PUT') @endif
		<div class="row g-3"><div class="col-md-6"><label class="form-label required" for="name">Name</label><input class="form-control" id="name" name="name" required value="{{ old('name', $credential->name) }}"></div><div class="col-md-6"><label class="form-label required" for="os">Platform</label><select class="form-select" id="os" name="os" required>@foreach ($oses as $os)<option value="{{ $os->value }}" @selected(old('os', $credential->os?->value) === $os->value)>{{ $os->label() }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label" for="username">Username</label><input class="form-control" id="username" name="username" value="{{ old('username', $credential->username) }}"><small class="form-hint">Blank uses the default runner username.</small></div><div class="col-md-6"><label class="form-label" for="password">Password</label><input class="form-control" id="password" name="password" type="password"><small class="form-hint">Leave blank to retain the existing password.</small></div><div class="col-12"><label class="form-label" for="private_key">SSH private key</label><textarea class="form-control font-monospace" id="private_key" name="private_key" rows="6"></textarea></div><div class="col-12"><label class="form-label" for="public_key">SSH public key</label><textarea class="form-control font-monospace" id="public_key" name="public_key" rows="3"></textarea><small class="form-hint">Provide both keys to enable SSH key authentication.</small></div></div>
		<div class="mt-4 text-end"><a class="btn btn-link" href="{{ route('settings.templates.credentials.index') }}">Cancel</a><button class="btn btn-primary" type="submit">{{ $credential->exists ? 'Save changes' : 'Create credential' }}</button></div>
	</form></div>
@endsection
